framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    asset_mapper:
        paths:
            - 'assets/'
    assets:
        enabled: true
        base_path: '/'
        
    session:
        handler_id: null
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: 'lax'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
