framework:
    messenger:
        failure_transport: failed

        transports:
            # Transport pour les messages envoyés synchrone
            sync: 'sync://'

            # Transport pour les messages asynchrones (envoi via une queue)
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2

            # Transport des échecs
            failed: 'doctrine://default?queue_name=failed'

        routing:
            # Exemple de routage des messages vers les transports
            # 'App\Message\YourMessage': async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
