security:
    # Hashers de mot de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Providers d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    # Hiérarchie des rôles (déplacée à l'extérieur de firewalls)
    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN]
        ROLE_EMPLOYEE: [ROLE_EMPLOYEE]
        ROLE_VETERINARY: [ROLE_VETERINARY]

    # Firewalls
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            entry_point: App\Security\LoginAuthenticator
            pattern: ^/
            custom_authenticators:
                - App\Security\LoginAuthenticator
            form_login:
                login_path: app_login
                check_path: app_login
            logout:
                path: app_logout
                target: app_home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                # always_remember_me: true

            switch_user: true

    # Access control pour les différentes sections
    access_control:
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_EMPLOYEE] }
        - { path: ^/employee, roles: [ROLE_EMPLOYEE] }
        - { path: ^/veterinary, roles: [ROLE_VETERINARY] }
        

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 6
                time_cost: 3
                memory_cost: 10
