# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    mongo_url: 'mongodb+srv://mel:rootmel@bootcamp.yrsi3.mongodb.net/' # Changez cette valeur selon votre configuration
    mongo_db: 'Zoo_Arcadia'
    app.jwtsecret : '%env(JWT_SECRET)%' 
    uploads_directory: '%kernel.project_dir%/public/uploads/' 

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
    Symfony\Component\Mailer\MailerInterface: '@mailer.mailer'

    App\Repository\ImagesRepository:
        arguments:
            $entityClass: 'App\Entity\Images'
    # App\Form\ReportsType:
    #     arguments:
    #         $animalsRepository: '@App\Repository\AnimalsRepository'
    #         $foodsRepository: '@App\Repository\FoodsRepository'
    #         $security: '@security.helper'
            
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Service\MongoDBService:
        arguments:
            $mongoUrl: '%mongo_url%'
            $databaseName: '%mongo_db%'
